import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'
import { CalendarDays, ChevronDown, ClipboardList, Languages, MoreVertical, Search, Send, ShieldAlert, Sparkles } from 'lucide-react'

type Draft = { draft_reply: string; detected_language: string; confidence: string; reason_if_needs_human: string | null }
const messages = [
  { initials:'MD', name:'Marion Dubois', property:'Casa Marbella · Apt 2B', time:'11:42 AM', channel:'AIRBNB', text:'Bonjour Elena, est-ce que le check-in anticipé vers 13h serait possible ?', status:'✦ Draft ready (98%)', active:true },
  { initials:'LO', name:"Liam O’Connor", property:'Casa Marbella · Penthouse', time:'09:15 AM', channel:'BOOKING.COM', text:'Regarding deposit refund for dates Nov 4–8. We experienced an issue with the...', status:'Host Attention Needed', active:false },
  { initials:'SV', name:'Sophie van der Beek', property:'Casa Marbella · Studio 1', time:'Yesterday', channel:'VRBO', text:'Keypad code received, thank you so much!', status:'✓ Resolved', active:false },
  { initials:'ML', name:'Marcus Lindholm', property:'Casa Marbella · Apt 2B', time:'Oct 12', channel:'AIRBNB', text:'Is parking on premises suitable for an...', status:'', active:false },
]
async function requestDraft(): Promise<Draft> { const r = await fetch('/api/replies/draft', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({message:messages[0].text, listing_id:'lst_001'}) }); if (!r.ok) throw new Error('Could not draft reply'); return r.json() }
export default function ReplyDrafter() {
  const [reply, setReply] = useState('Bonjour Marion ! Oui, tout à fait. L’équipe de ménage termine à 12h30, l’appartement sera donc parfaitement prêt pour vous à 13h00. Votre code de serrure connectée (4921#) s’activera automatiquement dès 13h. Bon voyage en train ! — Elena')
  const draft = useMutation({ mutationFn:requestDraft, onSuccess:(data) => setReply(data.draft_reply) })
  return <div className="inbox-layout grid min-h-[calc(100vh-7.5rem)] grid-cols-[minmax(300px,390px)_1fr] gap-4">
    <section className="overflow-hidden rounded-lg border border-border bg-white"><div className="p-5 pb-3"><h1 className="font-display text-2xl font-semibold">Unified Inbox</h1><p className="mt-1 font-mono text-[10px] text-muted"><i className="mr-1 inline-block h-2 w-2 rounded-full bg-accent"/>Co-Host Model: Lodgify Ops v4.2 · Auto-sync enabled</p><label className="mt-5 flex items-center gap-2 rounded bg-base px-3 py-3 text-sm text-muted"><Search size={17}/><input className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Filter messages, guests, units..."/></label><div className="mt-3 flex gap-1.5 font-mono text-[10px]"><span className="rounded-full bg-ink px-3 py-1 text-white">All (14)</span><span className="rounded-full bg-base px-3 py-1">Needs Action <b className="text-alert">2</b></span><span className="rounded-full bg-base px-3 py-1">Unread 3</span></div></div><div>{messages.map(m=><button key={m.name} className={`w-full border-t border-border/50 px-5 py-4 text-left hover:bg-base ${m.active?'border-l-4 border-l-ink bg-base':''}`}><div className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-border/60 font-mono text-xs">{m.initials}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="truncate text-sm">{m.name}{m.active&&<span className="ml-1 inline-block h-1.5 w-1.5 rounded-full bg-ink"/>}</b><span className="shrink-0 font-mono text-[10px]">{m.time}</span></div><div className="flex justify-between font-mono text-[10px] text-muted"><span>{m.property}</span><span className="rounded bg-base px-1">{m.channel}</span></div><p className="mt-1 line-clamp-2 text-sm text-muted">{m.text}</p>{m.status&&<span className={`mt-1 inline-block rounded px-1.5 py-1 font-mono text-[10px] ${m.active?'bg-accent':'bg-alert/10 text-alert'}`}>{m.status}</span>}</div></div></button>)}</div></section>
    <section className="flex min-w-0 flex-col overflow-hidden rounded-lg border border-border bg-white"><div className="grid grid-cols-[auto_1fr_auto] items-center gap-4 border-b border-border p-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-border/60 font-mono text-sm">MD</span><div><div className="flex items-center gap-2"><b>Marion Dubois</b><span className="font-mono text-xs">🇫🇷 FR · Auto-detected</span><span className="font-mono text-xs text-success">◉ Verified Guest</span></div><div className="mt-1 flex gap-5 font-mono text-[11px] text-muted"><span>Airbnb · #HM892K1L</span><span>Oct 18 – Oct 23 (5 nights)</span><span>€710 total</span><span>+33 6 42 98 12 04</span></div></div><div className="flex gap-2"><button className="icon-btn"><ClipboardList size={17}/></button><button className="icon-btn"><CalendarDays size={17}/></button><button className="icon-btn"><MoreVertical size={17}/></button></div></div>
      <div className="conversation flex-1 space-y-5 overflow-auto bg-base/60 px-7 py-6"><div className="mx-auto w-fit rounded bg-border/60 px-2 py-1 font-mono text-[10px] uppercase tracking-widest text-muted">Wednesday, Oct 16</div><article className="ml-10 rounded-lg border border-border/60 bg-white p-5"><div className="flex justify-between font-mono text-xs"><b>Elena Vance (Scheduled Guide)</b><span className="text-muted">2 days ago</span></div><p className="mt-2 text-sm leading-6">Bonjour Marion ! We look forward to hosting you at Casa Marbella (Apt 2B). Your standard check-in time is 3:00 PM. Here is the link to your digital welcome book with transit and building access instructions.</p></article><div className="text-right font-mono text-[10px] text-muted">Delivered via Airbnb Messaging</div><article className="mr-7 rounded-lg border border-border/60 bg-white p-5"><div className="flex justify-between font-mono text-xs"><b>Marion Dubois</b><span className="text-muted">11:42 AM</span></div><p className="mt-2 text-sm leading-6">Bonjour Elena ! Nous arrivons de Paris par le train du matin. Est-ce que le check-in anticipé vers 13h serait envisageable vendredi ? Merci beaucoup !</p><div className="mt-3 rounded bg-base p-3 font-mono text-xs text-muted"><Languages size={14} className="mr-2 inline"/>Translated automatically<br/><i className="font-sans text-sm">“Hello Elena! We arrive from Paris on the morning train. Would early check-in around 1pm be possible on Friday? Thank you very much!”</i></div></article><div className="font-mono text-[10px] text-muted">Seen just now</div></div>
      <div className="border-t border-border bg-white p-5"><div className="mb-3 flex flex-wrap items-center justify-between gap-2 font-mono text-[10px]"><span className="rounded bg-accent px-3 py-2 font-semibold"><Sparkles size={14} className="mr-1 inline"/>AI DRAFT · 98% CONFIDENCE</span><span className="text-muted">Verified against House Manual & Maid Service Schedule</span><span className="text-muted">Tone: Warm & Hospitality</span><span>Language: FR</span></div><div className="rounded border border-border border-l-[3px] border-l-accent p-4"><div className="flex justify-between font-mono text-[10px] text-muted"><span>Suggested response ready for human validation:</span><span>{draft.isPending?'Drafting…':'Drafted in 0.4s'}</span></div><textarea value={reply} onChange={e=>setReply(e.target.value)} className="mt-2 min-h-24 w-full resize-y text-sm leading-6 outline-none"/><div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={()=>draft.mutate()} disabled={draft.isPending} className="primary-btn"><Send size={15}/> Approve & Send <span className="font-mono text-[10px]">⌘↵</span></button><button className="secondary-btn">Edit Manually</button><button className="ghost-btn">Discard Draft</button><span className="ml-auto font-mono text-[10px] text-muted">◷ Code 4921# sync scheduled</span></div>{draft.isError&&<p className="mt-2 text-xs text-alert">{draft.error.message}</p>}</div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded bg-warn/15 p-3 text-xs text-ink"><div className="font-semibold"><ShieldAlert size={15} className="mr-2 inline text-warn"/>Low Confidence Safeguard</div><p className="mt-1 text-muted">Financial, refund, or dispute triggers automatically pause automated replies to protect host payout integrity.</p></div><div className="rounded bg-base p-3 font-mono text-[10px] text-muted"><ChevronDown className="mr-1 inline"/>Co-Host indexing Manual rules · Apt 2B Manual</div></div></div>
    </section>
  </div>
}
