import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { ArrowRight, Check, Clock3, Download, MessageSquare, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react'
import type { Screen } from '../App'
type Brief = {digest_id:string;period:string;headline_stat:{label:string;value:string;detail:string;potential_revenue_eur:number;occupancy_percent:number};flagged_issues:{type:string;title:string;detail:string;channel?:string;status?:string}[];suggested_action:{title:string;priority:string;detail:string;action:string}}
async function getBrief():Promise<Brief>{const r=await fetch('/api/brief/weekly');if(!r.ok)throw new Error('Unable to load weekly brief');return r.json()}
export default function WeeklyBrief({onNavigate}:{onNavigate:(s:Screen)=>void}){
 const {data,isPending,isError,error}=useQuery({queryKey:['weekly-brief'],queryFn:getBrief});const [applied,setApplied]=useState(false)
 return <div className="mx-auto max-w-[1080px]">{isPending&&<div className="status-card">Loading weekly brief…</div>}{isError&&<div className="status-card text-alert">{error.message}</div>}{data&&<><div className="mb-5 flex items-center justify-between"><h1 className="font-display text-lg font-semibold"><span className="mr-2 rounded bg-border/60 px-2 py-1 font-mono text-[10px]">DIGEST #42</span>Your week at a glance — {data.period}</h1><div className="flex items-center gap-4 font-mono text-[10px] text-muted">Generated Sunday 9:00am <button className="secondary-btn"><RefreshCw size={13}/>Regenerate</button></div></div>
  <section className="overflow-hidden rounded-lg border border-border border-t-[6px] border-t-accent bg-white p-8"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-lg bg-base text-success">⌂</div><div><h2 className="font-display text-lg font-semibold">Casa Marbella Portfolio</h2><p className="font-mono text-[11px] text-muted">3 active units · Marbella Old Town, Spain</p></div></div><span className="rounded bg-success/10 px-3 py-1 font-mono text-[10px] text-success">● Live Copilot Sync</span></div>
  <div className="mt-7 rounded-lg bg-base p-7"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="eyebrow text-ink">⚡ {data.headline_stat.label}</div><h3 className="mt-2 font-display text-4xl font-semibold">{data.headline_stat.value}</h3><p className="mt-2 text-sm text-muted">{data.headline_stat.detail}. Potential revenue: <b className="text-ink">€{data.headline_stat.potential_revenue_eur}</b>.</p></div><div className="text-right"><b className="font-display text-3xl">{data.headline_stat.occupancy_percent}%</b><p className="font-mono text-[10px] text-muted">projected occupancy</p></div></div><div className="mt-6 rounded-lg bg-white p-4"><div className="flex justify-between font-mono text-[10px]"><span>🟡 7-Day Pace Trend (Sep 21 – Sep 27)</span><span>Peak: Saturday (94%)</span></div><div className="mt-5 flex h-24 items-end justify-between border-b border-border px-2"><svg className="h-full w-full overflow-visible" viewBox="0 0 800 110" preserveAspectRatio="none"><path d="M5 88 C130 82 150 65 270 59 S420 32 520 37 S680 6 795 32" fill="none" stroke="currentColor" className="text-ink" strokeWidth="3"/><path d="M5 88 C130 82 150 65 270 59 S420 32 520 37 S680 6 795 32 L795 110 L5 110Z" fill="currentColor" className="text-accent" opacity=".25"/><circle cx="590" cy="26" r="8" fill="currentColor" className="text-accent" stroke="currentColor" strokeWidth="3"/></svg></div><div className="mt-2 flex justify-between font-mono text-[9px] text-muted"><span>Mon 21 (71%)</span><span>Tue 22</span><span>Wed 23 (79%)</span><span>Thu 24</span><span>Fri 25 (86%)</span><span>Sat 26 (94%)</span><span>Sun 27 ({data.headline_stat.occupancy_percent}%)</span></div></div><div className="mt-4 grid gap-3 md:grid-cols-3">{[['PROJECTED REVENUE','€3,280','Gross booked + projected'],['AVG DAILY RATE','€164','+€12 over September benchmark'],['PACING TRAJECTORY','+14% ↗','vs. same week last year']].map(x=><div className="rounded bg-white p-4" key={x[0]}><div className="eyebrow">{x[0]}</div><b className="mt-1 block font-display text-xl">{x[1]}</b><span className="text-xs text-muted">{x[2]}</span></div>)}</div></div>
  <div className="mt-8"><div className="mb-3 flex justify-between font-mono text-[10px] uppercase tracking-widest text-muted"><span>Actionable Operations ({data.flagged_issues.length})</span><span>All channels synchronized</span></div><div className="space-y-1">{data.flagged_issues.map((issue,i)=><div className="flex items-center gap-4 rounded bg-base p-4" key={issue.title}><span className={`rounded-lg p-2 ${i===0?'bg-accent':'bg-border/60'}`}>{i===0?<MessageSquare size={18}/>:i===1?<Clock3 size={18} className="text-alert"/>:<Check size={18} className="text-success"/>}</span><div className="flex-1"><div className="flex items-center gap-2 text-sm font-semibold">{issue.title}<span className="rounded bg-success/10 px-1.5 py-0.5 font-mono text-[9px] text-success">{issue.channel??issue.status}</span></div><p className="mt-1 text-xs text-muted">{issue.detail}</p></div><button onClick={()=>onNavigate(i===0?'Inbox':'Conflicts')} className="whitespace-nowrap text-xs font-semibold">{i===0?'Preview Reply':'Jump to Inbox'} <ArrowRight size={14} className="inline"/></button></div>)}</div></div>
  <div className="mt-7 rounded-lg bg-border/30 p-6"><div className="flex items-center justify-between"><h3 className="font-display font-semibold"><Sparkles size={18} className="mr-2 inline text-warn"/>Copilot Recommendation: {data.suggested_action.title}</h3><span className="rounded bg-accent px-2 py-1 font-mono text-[10px]">Priority {data.suggested_action.priority}</span></div><p className="mt-3 max-w-3xl text-sm leading-6 text-muted">{data.suggested_action.detail}</p><div className="mt-4 flex gap-3"><button onClick={()=>setApplied(true)} className="primary-btn"><Check size={15}/>{applied?'Applied to Airbnb Calendar':data.suggested_action.action}</button><button className="ghost-btn">Dismiss</button></div></div>
  <footer className="mt-8 flex justify-between font-mono text-[10px] text-muted"><span><ShieldCheck size={13} className="mr-1 inline"/>Prepared by Host Copilot for Elena Vance</span><span>Next brief scheduled Oct 5 at 9:00 AM CEST</span></footer></section><div className="flex justify-between px-2 py-4 text-xs text-muted"><div className="flex gap-4"><button><Download size={13} className="mr-1 inline"/>Download as PDF</button><button>Adjust Notification Settings</button></div><span>Brief ID: #{data.digest_id}</span></div></>}</div>
}
